application: multi-user 
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /.*
  script: src.handlers.app

skip_files:
- ^(node_modules/.*)
- .DS_Store
